language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: aladage@gmail.com
  api_key:
    secure: lQlgNQqx1B1kRuVYnDupH17o0EiLCA0mWlunKjhln+18t97R2DcE5QxSuSwxcbFJjt1vPCZa/VJ2uC3Ng4tKlXmRLwxoDKlBb371b/dzfmAfZ56iiQ6Ymtg9oenTnP2htMFKE1324ojmy6L78vZDdiW+bv5C5NfR/EeTFAmPY6LXqYUhLbqIBz2q2GnIdd9kB8e0MtC3TLQSdjy2q1VpLJXIWb4O5sR1x9kN2mVhDayHFoX+7t5Q+LjjaoEV/qs7ZGRWIoLR17Seg9E1V40SPXKmcqQ3bJdN9+zlmFCNUz3UI3K5lClMlkGdoRcjmVLQrp4vmjBRACRxt9eyQusxoQlGbDHqjNfR7LM8HuL8ro+WLveQR+JlShnImzI9IMJiZCw9xs6IluiXuvrscdbwVDXDQwLd/DdXuQweGvWKjxtckZU0mNMLVPl7UuhOBB2HolS4NqMPJmEziSFqB+Fwl5CvKarVjkwRm6216L80rIXUM0ozywvAHRQlPDkz6WMj6xH4Y5bFoIVoIKDBcQ2tFwULlAsqx7QTzweEQEP5Br/lC3N5Brx5Opt/suMWiQwhXKg2rIthDCG1zZM3AXs3p1MPDFhQaYut+C4aTNjRq7ppcOXvUAJEbP/E7ZtXElwyKd4lvfKyGpEXO9DeavnS7kYEOt7wIPwdBOY3HFHrLq0=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/orko
