module.exports = {
    hello: ` *** Hi, I'm Orko! I can help get your Skeletor project up and running quickly. *** `,
    packageAlreadyExists: `A package.json file already exists for this project. Continuing will overwrite it. Are you sure you want to continue?`,
    packageCreationError: `There was an error creating the package.json file.`,
    packageCreationCanceled: `Package creation canceled.`,
    onboardingQuestionsThanks: `Thanks for the input! That's all I need for now. Sit back while I set up your project...`,
    downloadingTemplate: `Downloading {{platform}} template files from {{url}}...`,
    downloadingTemplateComplete: `Template download complete.`,
    installingNpmDependencies: `Installing NPM dependencies...`,
    npmDependenciesInstallSuccess: `NPM dependencies installation complete.`,
    runningSkeletorInstallTask: `Running the Skeletor install task for this template...`,
    skeletorInstallTaskSuccess: `Skeletor install task complete.`,
    runningTemplatePostInstall: `Running postinstall tasks for this template...`,
    runningTemplateHook: `Running the template's {{hookName}} hook...`,
    templateHookSuccess: `Template's {{hookName}} hook complete.`,
    templatePostInstallSuccess: `Template postinstall tasks complete.`,
    copying: `Copying {{src}} to {{dest}}`,
    copyingTmpToProject: `Copying working files into your project's directory.`,
    orkoJunkCleanup: `Cleaning up after myself, almost finished.`,
    goodbye: `I'm all done. Type "skel build" to run your first build task, and check out your skeletor.config.js file for other available tasks. Goodbye!`
};